apiVersion: v1
kind: Service
metadata:
  name: redis-metrics
spec:
  selector:
    app: adapter
  ports:
  - port: 9121
    targetPort: 9121

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-example
spec:
  selector:
    matchLabels:
      app: adapter
  template:
    metadata:
      labels:
        app: adapter
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: adapter
        image: oliver006/redis_exporter
        ports:
        - containerPort: 9121
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
