apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.3
        volumeMounts:
        - name: config
          mountPath: /tmp/git
        env:
        - name: GIT_SYNC_ROOT
          value: /tmp/git
        - name: GIT_SYNC_REPO
          value: https://github.com/jesulink2514/central-config
        - name: GIT_SYNC_LINK
          value: ./config
        - name: GIT_SYNC_BRANCH
          value: main
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
      - name: web
        image: jesulink2514.docker.io/regular-webapp
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: /app/config
        env:
        - name: DOTNET_USE_POLLING_FILE_WATCHER 
          value: "true"
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
          - containerPort: 8080
      volumes:
      - name: config
        emptyDir: {}