apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sharded-redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: "redis"
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379

---
apiVersion: v1
kind: Pod
metadata:
  name: ambassador-example
spec:
  containers:
    # This is where the application container would go, for example
    - name: app
      image: goodsmileduck/redis-cli
      command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 6 ; done"]
      resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
    # This is the ambassador container
    - name: twemproxy
      image: ganomede/twemproxy
      command: [ "nutcracker", "-c", "/etc/config/nutcracker.yaml", "-v", "7", "-s", "6222" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
      resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
  volumes:
    - name: config-volume
      configMap:
        # This is the ConfigMap object we created using 'nutcracker.yaml'
        name: twem-config