apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary
spec:
  selector:
    matchLabels:
      app: dictionary
  replicas: 3
  template:
    metadata:
      labels:
        app: dictionary
    spec:
      containers:
      - name: dictionary
        image: jesulink2514.docker.io/dictionary-server
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: dictionary-server
spec:
  selector:
    app: dictionary
  ports:
  - port: 8080
    targetPort: 8080
