apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ssl
spec:
  selector:
    matchLabels:
      app: nginx-ssl
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx-ssl
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 443
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx
        - name: certs
          mountPath: /etc/certs
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
      volumes:
      - name: conf
        configMap:
          name: nginx-conf
      - name: certs
        secret:
          secretName: nginx-ssl
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-ssl
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
